apiVersion: v1
kind: Service
metadata:
  labels:
    run: soa-demo-consumer
  name: soa-demo-consumer
  namespace: ees
spec:
  clusterIP: 10.101.122.212
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    run: soa-demo-consumer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
