apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: soa-demo-provider 
  name: soa-demo-provider 
  namespace: ees
spec:
  replicas: 1
  selector:
    matchLabels:
      run: soa-demo-provider
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: soa-demo-provider
    spec:
      containers:
      - command:
        - java 
        - -Xmx512m 
        - -Duser.timezone=Asia/Shanghai 
        - -Djava.security.egd=file:/dev/./urandom 
        - -jar
        - /app/demo-provider.jar 
        - --server.port=8001 
        - --eureka.instance.instanceId=soa-demo-provider-10.20.0.6:8001 
        - --eureka.client.serviceUrl.defaultZone=http://10.20.0.25:8080/eureka/
        - --eureka.instance.preferIpAddress=true
        image: registry.cloud.ixicar.cn/library/soa-demo-provider:1.0.0
        imagePullPolicy: IfNotPresent
        name: soa-demo-provider
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-config
          readOnly: true
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: tz-config
      nodeSelector:
        name: node-07
