apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: soa-demo-consumer 
  name: soa-demo-consumer 
  namespace: ees
spec:
  replicas: 1
  selector:
    matchLabels:
      run: soa-demo-consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: soa-demo-consumer
    spec:
      containers:
      - command:
        - java 
        - -Xmx512m 
        - -Duser.timezone=Asia/Shanghai 
        - -Djava.security.egd=file:/dev/./urandom 
        - -jar
        - /app/demo-consumer.jar
        - --server.port=8002 
        - --eureka.instance.instanceId=soa-demo-consumer-10.20.0.6:8001 
        - --eureka.client.serviceUrl.defaultZone=http://10.20.0.25:8080/eureka/
        image: registry.cloud.ixicar.cn/library/soa-demo-consumer:1.0.0
        imagePullPolicy: IfNotPresent
        name: soa-demo-consumer
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-config
          readOnly: true
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: tz-config
